### ISSUE TITLE
Case issue on the latest develop

### ISSUE THREAD

**Issue by BasileTrujillo** [getgrav/grav-plugin-problems#20]
Hello,

I found a problem in the problems plugin :)
On the latest commit at "v2.0 Rewrite (#19)".
On Unix system I got the following error : 

```
[2018-09-20 10:00:41] grav.CRITICAL: DirectoryIterator::__construct(/var/app/current/user/plugins/problems/classes/problems): failed to open dir: No such file or directory - Trace: #0 /var/app/current/user/plugins/problems/classes/Problems/Base/ProblemChecker.php(59): DirectoryIterator->__construct('/var/app/curren...') #1 /var/app/current/user/plugins/problems/problems.php(82): Grav\Plugin\Problems\Base\ProblemChecker->check('/var/app/curren...') #2 /var/app/current/user/plugins/problems/problems.php(32): Grav\Plugin\ProblemsPlugin->problemsFound() #3 /var/app/current/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\ProblemsPlugin->onFatalException(Object(RocketTheme\Toolbox\Event\Event), 'onFatalExceptio...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #4 /var/app/current/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onFatalExceptio...', Object(RocketTheme\Toolbox\Event\Event)) #5 /var/app/current/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onFatalExceptio...', Object(RocketTheme\Toolbox\Event\Event)) #6 /var/app/current/system/src/Grav/Common/Grav.php(279): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onFatalExceptio...', Object(RocketTheme\Toolbox\Event\Event)) #7 /var/app/current/index.php(54): Grav\Common\Grav->fireEvent('onFatalExceptio...', Object(RocketTheme\Toolbox\Event\Event)) #8 {main} [] []
```

The issue seams to be located at `problems.php` L82 :

```php
private function problemsFound()
    {
        $status = $this->checker->check(__DIR__ . '/classes/problems');
        $this->problems = $this->checker->getProblems();
        
        return $status;
    }
```

This function try to `check()` with  `__DIR__ . '/classes/problems'` instead of `__DIR__ . '/classes/Problems'`.

Regards

**Comment by rhukster** [comment]
Good catch. I changed the case of the actual folders after and never updated that function.
